In [7]:
# import libraries
from datetime import datetime, timedelta
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from __future__ import division

import chart_studio
chart_studio.tools.set_credentials_file(username='kwanjeff', api_key='8tHTqA70hAglUEyeYjlu')

import chart_studio.plotly as py
import plotly.offline as pyoff
import plotly.graph_objs as go

#initiate visualization library for jupyter notebook 
#pyoff.init_notebook_mode()

tx_data = pd.read_csv(r'.\OnlineRetail.csv', encoding='unicode_escape')

tx_data.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [4]:
import chart_studio
chart_studio.tools.set_credentials_file(username='kwanjeff', api_key='8tHTqA70hAglUEyeYjlu')

Requirement already satisfied: chart-studio in d:\programdata\anaconda3\lib\site-packages (1.0.0rc1)
Requirement already satisfied: plotly in d:\programdata\anaconda3\lib\site-packages (from chart-studio) (4.14.3)
Requirement already satisfied: requests in d:\programdata\anaconda3\lib\site-packages (from chart-studio) (2.25.1)
Requirement already satisfied: six in d:\programdata\anaconda3\lib\site-packages (from chart-studio) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in d:\programdata\anaconda3\lib\site-packages (from chart-studio) (1.3.3)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\programdata\anaconda3\lib\site-packages (from requests->chart-studio) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\programdata\anaconda3\lib\site-packages (from requests->chart-studio) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\programdata\anaconda3\lib\site-packages (from requests->chart-studio) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in d:\programdata\anaconda3\lib\site-packages (from requests->chart-studio) (2.10)
Note: you may need to restart the kernel to use updated packages.