Task numbering 
1 - data masaaging and showing data 

2 - correlation testing and dropping correlated data 

3 - convert to dummy 

4 - Train data/ fit data / scale 


5 - export scaled and fit data

In [1]:
#Task 1.0  import libraries 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from  sklearn import preprocessing

In [2]:
#Task 1.1  import csv file
UsedVehicle=pd.read_csv(r'.\Data\UsedCarData\clean_vehicles.csv')

In [3]:
#Task 1.2  

UsedVehicle.head(10)

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,drive,size,type,paint_color,image_url,description,state,lat,long,posting_date
0,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,...,unknown,unknown,pickup,white,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:18-05:00
1,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,unknown,unknown,pickup,blue,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:08-05:00
2,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,unknown,unknown,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:25-05:00
3,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,unknown,unknown,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 10:41:31-05:00
4,7316356412,https://auburn.craigslist.org/cto/d/auburn-uni...,auburn,https://auburn.craigslist.org,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,...,rwd,full-size,truck,black,https://images.craigslist.org/00404_l4loxHvdQe...,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,2021-05-03 14:02:03-05:00
5,7316343444,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,27990,2012.0,gmc,sierra 2500 hd extended cab,good,8 cylinders,...,4wd,unknown,pickup,black,https://images.craigslist.org/00V0V_ftJbKrOgdi...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03 13:41:25-05:00
6,7316304717,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,34590,2016.0,chevrolet,silverado 1500 double,good,6 cylinders,...,4wd,unknown,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03 12:41:33-05:00
7,7316285779,https://auburn.craigslist.org/cto/d/auburn-201...,auburn,https://auburn.craigslist.org,35000,2019.0,toyota,tacoma,excellent,6 cylinders,...,4wd,unknown,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,al,32.6013,-85.443974,2021-05-03 12:12:59-05:00
8,7316257769,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,29990,2016.0,chevrolet,colorado extended cab,good,6 cylinders,...,4wd,unknown,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03 11:31:14-05:00
9,7316133914,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,38590,2011.0,chevrolet,corvette grand sport,good,8 cylinders,...,rwd,unknown,other,red,https://images.craigslist.org/00U0U_kKYnS1LWh8...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03 07:50:35-05:00

In [4]:
#Task 1.3
UsedVehicle.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'state', 'lat', 'long', 'posting_date'],
      dtype='object')

In [6]:
#Task 1.4
# need to drop this column as id is not a measurable column
UsedVehicle.drop(UsedVehicle[['id','url','image_url']].columns,axis=1,inplace = True)

In [7]:
#Task 1.5

UsedVehicle.describe()

              price           year      odometer
count  4.161490e+05  416149.000000  4.161490e+05
mean   6.158955e+04    2011.365749  9.766435e+04
std    1.108080e+07       9.140825  2.046903e+05
min    0.000000e+00    1900.000000  0.000000e+00
25%    5.995000e+03    2008.000000  3.800000e+04
50%    1.399100e+04    2014.000000  8.568200e+04
75%    2.650000e+04    2017.000000  1.335030e+05
max    3.736929e+09    2022.000000  1.000000e+07

In [8]:
#Task 1.6 converting values in the column in this cell to be a more managable numbers.  Using Log1p function.  
# log1p is used instead of log because there is a column AMT_ANNUITY with value of 0

num_features=['price','odometer']

for feature in num_features:
    UsedVehicle[feature]=np.log1p(UsedVehicle[feature])

In [9]:
#Task 1.6
UsedVehicle.describe()

               price           year       odometer
count  416149.000000  416149.000000  416149.000000
mean        8.732425    2011.365749      10.938864
std         2.712483       9.140825       1.621054
min         0.000000    1900.000000       0.000000
25%         8.698848    2008.000000      10.545368
50%         9.546241    2014.000000      11.358410
75%        10.184938    2017.000000      11.801887
max        22.041530    2022.000000      16.118096

In [16]:
UsedVehicle.head()

,region,region_url,price,year,manufacturer,model,condition,cylinders,fuel,odometer,...,VIN,drive,size,type,paint_color,description,state,lat,long,posting_date
0,auburn,https://auburn.craigslist.org,10.422013,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,gas,10.966887,...,3GTP1VEC4EG551563,unknown,unknown,pickup,white,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:18-05:00
1,auburn,https://auburn.craigslist.org,10.025307,2010.0,chevrolet,silverado 1500,good,8 cylinders,gas,11.173669,...,1GCSCSE06AZ123805,unknown,unknown,pickup,blue,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:08-05:00
2,auburn,https://auburn.craigslist.org,10.586357,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,gas,9.860632,...,3GCPWCED5LG130317,unknown,unknown,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 12:31:25-05:00
3,auburn,https://auburn.craigslist.org,10.341452,2017.0,toyota,tundra double cab sr,good,8 cylinders,gas,10.624371,...,5TFRM5F17HX120972,unknown,unknown,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04 10:41:31-05:00
4,auburn,https://auburn.craigslist.org,9.615872,2013.0,ford,f-150 xlt,excellent,6 cylinders,gas,11.759793,...,blank,rwd,full-size,truck,black,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,2021-05-03 14:02:03-05:00

In [10]:
# Task 2.0.0
# with the following function we can select highly correlated features
# it will identify so I can remove the first feature that is correlated with anything other feature

def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    #corr_matrix = dataset.corr()
    df= dataset.drop(columns='price')
    #df= dataset.drop(colums= 'Late_Payments')#doing this step above to 
    df_corr= df.corr()
    for i in range(len(df_corr.columns)):
        for j in range(i):
            if abs(df_corr.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname = df_corr.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [11]:
#Task 2.1.1
corr_features = correlation(UsedVehicle , 0.7)#coefficent corelated if 70%, 
                                        #if i adjust threshold i can control how many feature to drop. 

len(set(corr_features))

0

In [12]:
#Task 2.1.2
# after doing a
corr_features

set()

In [17]:
#Task 3
dummy=pd.get_dummies(UsedVehicle)

MemoryError: Unable to allocate 12.4 GiB for an array with shape (115512, 115512) and data type uint8

In [ ]:
#Task 3.1
dummy.shape

In [ ]:
#Task 3.2
dummy

In [ ]:
#Task 3.3
X=dummy.drop(columns='LATE_PAYMENT')
y=dummy['LATE_PAYMENT']

X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=dummy['LATE_PAYMENT'], test_size=0.25)
#remove train and split and data and will be placed into end of features